name: boozin_fitness
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  # getx for state management
  get: 4.6.6
  # health to connect with google fit
  health: 9.0.1
  # to show svg icons
  flutter_svg: 2.0.10+1
  # for formatting
  intl: 0.19.0
  # local storage
  get_storage: 2.1.1
  # lottie animations
  lottie: ^3.1.0
  # native splash
  flutter_native_splash: ^2.3.13
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 3.0.1
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#181818"
  image: assets/images/Boozin_logo_light.png
  image_dark: assets/images/Boozin_logo_dark.png
  android: true
  ios: true
  android_12:
    color: "#FFFFFF"
    color_dark: "#181818"
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#181818"
    image: assets/images/Boozin_logo_light.png
    image_dark: assets/images/Boozin_logo_dark.png

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900
